// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DS_Wortschatz.Models;

public partial class AdminGame
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int IdW { get; set; }

    public int DartikelId { get; set; }

    public int SartikelId { get; set; }
}