// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DS_Wortschatz.Models;

public partial class Stat
{
    public int Uid { get; set; }

    public int PlayTotal { get; set; }

    public DateTime PlayLast { get; set; }

    public int CorrectWords { get; set; }

    public int WrongWords { get; set; }
}